// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXiEiGVREEyxwJh1RHUbDiSdUcJg0WuAw',
    appId: '1:1064638638062:web:14b43cbe6c0c7539fa90ff',
    messagingSenderId: '1064638638062',
    projectId: 'softtech-scratch-n-win',
    authDomain: 'softtech-scratch-n-win.firebaseapp.com',
    storageBucket: 'softtech-scratch-n-win.firebasestorage.app',
    measurementId: 'G-W3QP3LZLGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaVMclD68vrWw4cAP-iiXrNByxNUu7ya4',
    appId: '1:1064638638062:android:2c40d2b24a68385ffa90ff',
    messagingSenderId: '1064638638062',
    projectId: 'softtech-scratch-n-win',
    storageBucket: 'softtech-scratch-n-win.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_AZRYEiEBL0znuKHweOwEsS5wW5BmCY',
    appId: '1:1064638638062:ios:19a2704d90494d57fa90ff',
    messagingSenderId: '1064638638062',
    projectId: 'softtech-scratch-n-win',
    storageBucket: 'softtech-scratch-n-win.firebasestorage.app',
    iosBundleId: 'com.example.softechScratchNWin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ_AZRYEiEBL0znuKHweOwEsS5wW5BmCY',
    appId: '1:1064638638062:ios:19a2704d90494d57fa90ff',
    messagingSenderId: '1064638638062',
    projectId: 'softtech-scratch-n-win',
    storageBucket: 'softtech-scratch-n-win.firebasestorage.app',
    iosBundleId: 'com.example.softechScratchNWin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXiEiGVREEyxwJh1RHUbDiSdUcJg0WuAw',
    appId: '1:1064638638062:web:06476789bcd475bffa90ff',
    messagingSenderId: '1064638638062',
    projectId: 'softtech-scratch-n-win',
    authDomain: 'softtech-scratch-n-win.firebaseapp.com',
    storageBucket: 'softtech-scratch-n-win.firebasestorage.app',
    measurementId: 'G-46VSM1K8NM',
  );
}
